# Generated by Django 5.0.1 on 2024-01-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('narx', models.PositiveIntegerField()),
                ('yangi', models.BooleanField()),
                ('rasm', models.FileField(upload_to='')),
            ],
        ),
    ]
