# Generated by Django 5.0.1 on 2024-01-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sotuv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('sana', models.DateField()),
                ('talaba_soni', models.BigIntegerField()),
                ('sayt', models.CharField(max_length=100)),
                ('yillik', models.CharField(max_length=6)),
                ('rasmi', models.FileField(upload_to='')),
            ],
        ),
    ]
