# Generated by Django 5.0.1 on 2024-01-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sotuv', '0003_alter_universiter_nomi_alter_universiter_rasmi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universiter',
            name='sana',
            field=models.DateField(auto_now_add=True),
        ),
    ]
