# Generated by Django 5.0.1 on 2024-01-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sotuv', '0004_alter_universiter_sana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foydalanuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('login', models.CharField(default=True, max_length=20)),
                ('parol', models.IntegerField(default=True)),
                ('email', models.CharField(max_length=6)),
                ('talaba', models.BooleanField(default=True)),
                ('resm', models.FileField(blank=True, null=True, unique=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('yosh', models.IntegerField()),
                ('jinsi', models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=6)),
            ],
        ),
    ]
