# Generated by Django 5.0.1 on 2024-01-13 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sotuv', '0005_foydalanuvchi_talaba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktyor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('tugilgan_yil', models.DateField()),
                ('davlat', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rejissor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('yosh', models.IntegerField()),
                ('kinolar_soni', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='login',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='parol',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Kino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('yil', models.DateField()),
                ('janr', models.CharField(max_length=20)),
                ('aktyorlar', models.ManyToManyField(to='sotuv.aktyor')),
                ('rejissor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sotuv.rejissor')),
            ],
        ),
    ]
