# Generated by Django 5.0.1 on 2024-01-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sotuv', '0006_aktyor_rejissor_alter_foydalanuvchi_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktyor',
            name='tugilgan_yil',
            field=models.PositiveIntegerField(),
        ),
    ]
