# Generated by Django 5.0.1 on 2024-01-13 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sotuv', '0007_alter_aktyor_tugilgan_yil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('daraja', models.CharField(choices=[('boshlangich', 'boshlangich'), ('orta', 'orta'), ('yuqori', 'yuqori')], max_length=20)),
                ('narx', models.IntegerField()),
                ('chegirma', models.CharField(default=0, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=20)),
                ('yosh', models.CharField(max_length=20)),
                ('jins', models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baho', models.IntegerField(blank=True, null=True)),
                ('matn', models.TextField()),
                ('sana', models.DateField()),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sotuv.kurs')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sotuv.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Xarid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('holat', models.CharField(choices=[('tugadi', 'tugadi'), ('davomiy', 'davomiy'), ('boshlanmagan', 'boshlanmagan')], max_length=20)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sotuv.kurs')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sotuv.profil')),
            ],
        ),
    ]
