# Generated by Django 5.0.1 on 2024-01-13 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sotuv', '0008_kurs_profil_izoh_xarid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izoh',
            name='baho',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
