# Generated by Django 5.0.1 on 2024-01-27 10:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sotuv', '0010_tanlangan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imtixon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzil', models.CharField(max_length=30)),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sotuv.talaba')),
                ('universitet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sotuv.universiter')),
            ],
        ),
        migrations.CreateModel(
            name='Natija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(189), django.core.validators.MinValueValidator(0)])),
                ('natija', models.CharField(choices=[('budjet', 'budjet'), ('kontrakt', 'kontrakt'), ('superkontrakt', 'superkontrakt'), ('Yiqildi', 'Yiqildi')], max_length=30)),
                ('imtixon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sotuv.imtixon')),
            ],
        ),
        migrations.CreateModel(
            name='Nazoratchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('kasb', models.CharField(max_length=30)),
                ('imtihon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sotuv.imtixon')),
            ],
        ),
    ]
